name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./authormanage/pom.xml
          mvn clean package -f ./writingmangaement/pom.xml
          mvn clean package -f ./aimanagement/pom.xml
          mvn clean package -f ./bookmanagement/pom.xml
          mvn clean package -f ./user/pom.xml
          mvn clean package -f ./pointmanagement/pom.xml
          mvn clean package -f ./BoundedContext2063/pom.xml

      - name: Docker Build and push for Authormanage
        uses: docker/build-push-action@v4
        with:
          context: ./authormanage
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/authormanage:latest
            ghcr.io/${{ github.repository }}/authormanage:${{ github.ref_name }}
            
      - name: Docker Build and push for Writingmangaement
        uses: docker/build-push-action@v4
        with:
          context: ./writingmangaement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/writingmangaement:latest
            ghcr.io/${{ github.repository }}/writingmangaement:${{ github.ref_name }}
            
      - name: Docker Build and push for Aimanagement
        uses: docker/build-push-action@v4
        with:
          context: ./aimanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/aimanagement:latest
            ghcr.io/${{ github.repository }}/aimanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Bookmanagement
        uses: docker/build-push-action@v4
        with:
          context: ./bookmanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bookmanagement:latest
            ghcr.io/${{ github.repository }}/bookmanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for User
        uses: docker/build-push-action@v4
        with:
          context: ./user
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/user:latest
            ghcr.io/${{ github.repository }}/user:${{ github.ref_name }}
            
      - name: Docker Build and push for Pointmanagement
        uses: docker/build-push-action@v4
        with:
          context: ./pointmanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/pointmanagement:latest
            ghcr.io/${{ github.repository }}/pointmanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for BoundedContext2063
        uses: docker/build-push-action@v4
        with:
          context: ./BoundedContext2063
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/boundedcontext2063:latest
            ghcr.io/${{ github.repository }}/boundedcontext2063:${{ github.ref_name }}
            
