server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: authormanage
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**, 
        - id: writingmangaement
          uri: http://localhost:8083
          predicates:
            - Path=/writings/**, 
        - id: aimanagement
          uri: http://localhost:8084
          predicates:
            - Path=/coverDesigns/**, /contentAnalyzers/**, 
        - id: bookmanagement
          uri: http://localhost:8085
          predicates:
            - Path=/books/**, 
        - id: user
          uri: http://localhost:8086
          predicates:
            - Path=/users/**, /subscriptions/**, 
        - id: pointmanagement
          uri: http://localhost:8087
          predicates:
            - Path=/points/**, /bookPrices/**
        - id: BoundedContext2063
          uri: http://localhost:8088
          predicates:
            - Path=, /users/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: authormanage
          uri: http://authormanage:8080
          predicates:
            - Path=/authors/**, 
        - id: writingmangaement
          uri: http://writingmangaement:8080
          predicates:
            - Path=/writings/**, 
        - id: aimanagement
          uri: http://aimanagement:8080
          predicates:
            - Path=/coverDesigns/**, /contentAnalyzers/**, 
        - id: bookmanagement
          uri: http://bookmanagement:8080
          predicates:
            - Path=/books/**, 
        - id: user
          uri: http://user:8080
          predicates:
            - Path=/users/**, /subscriptions/**, 
        - id: pointmanagement
          uri: http://pointmanagement:8080
          predicates:
            - Path=/points/**, 
        - id: BoundedContext2063
          uri: http://boundedContext2063:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
