---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authormanage
  labels:
    app: authormanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authormanage
  template:
    metadata:
      labels:
        app: authormanage
    spec:
      containers:
        - name: authormanage
          image: username/authormanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: writingmangaement
  labels:
    app: writingmangaement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writingmangaement
  template:
    metadata:
      labels:
        app: writingmangaement
    spec:
      containers:
        - name: writingmangaement
          image: username/writingmangaement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aimanagement
  labels:
    app: aimanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aimanagement
  template:
    metadata:
      labels:
        app: aimanagement
    spec:
      containers:
        - name: aimanagement
          image: username/aimanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmanagement
  labels:
    app: bookmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmanagement
  template:
    metadata:
      labels:
        app: bookmanagement
    spec:
      containers:
        - name: bookmanagement
          image: username/bookmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: username/user:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pointmanagement
  labels:
    app: pointmanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pointmanagement
  template:
    metadata:
      labels:
        app: pointmanagement
    spec:
      containers:
        - name: pointmanagement
          image: username/pointmanagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext2063
  labels:
    app: BoundedContext2063
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext2063
  template:
    metadata:
      labels:
        app: BoundedContext2063
    spec:
      containers:
        - name: BoundedContext2063
          image: username/BoundedContext2063:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: authormanage
  labels:
    app: authormanage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: authormanage


---


apiVersion: v1
kind: Service
metadata:
  name: writingmangaement
  labels:
    app: writingmangaement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: writingmangaement


---


apiVersion: v1
kind: Service
metadata:
  name: aimanagement
  labels:
    app: aimanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: aimanagement


---


apiVersion: v1
kind: Service
metadata:
  name: bookmanagement
  labels:
    app: bookmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: user


---


apiVersion: v1
kind: Service
metadata:
  name: pointmanagement
  labels:
    app: pointmanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pointmanagement


---


apiVersion: v1
kind: Service
metadata:
  name: BoundedContext2063
  labels:
    app: BoundedContext2063
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BoundedContext2063

